config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'boot_status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/views/admin/index.html.haml
%div.modal#modal-create-instructor{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title= "Create Instructor"
      %div.modal-body#modalbody
        = form_tag admin_instructor_create_path(), remote:true, method: :post do 
          %div#email-div
            This will assign a random password for the instructor and will automatically send an email to the instructor with their credentials.
            %p
            = label_tag nil, 'Email:', class: 'control-label'
            = text_field_tag :email, nil, class: 'form-control'
            %span.help-block.inline#email-help
          %div#name-div
            = label_tag nil, 'Name:', class: 'control-label'
            = text_field_tag :name, nil, class: 'form-control'
            %span.help-block.inline#name-help
          %div#organization-div
            = label_tag nil, 'Organization:', class: 'control-label'
            = text_field_tag :organization, nil, class: 'form-control'
            %span.help-block.inline#organization-help
          %p
          = submit_tag 'Create', :class => 'btn btn-default'

      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.modal#modal-student-group-create{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Create Student Group
      %div.modal-body#modalbody
        = form_tag admin_student_group_create_path(@scenario), remote: true, method: :post do 
          %div#name-div
            = label_tag nil, "Name:"
            = text_field_tag "name", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %br
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.modal#modal-student-group-user-add{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Add User to Student Group
      %div.modal-body#modalbody
        = form_tag admin_student_group_user_add_path(@scenario), remote: true, method: :post do
          = label_tag nil, "User:"
          %span#user-name
          = hidden_field_tag 'user_id'
          %div#name-div
            = label_tag nil, "Student Group Name:"
            = text_field_tag "student_group_name", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %br
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h3
        Admin Home

  %div.panel-body
    %label Account Information: 
    %div
      %dl
        Name: 
        =@user.name
        %br
        Email:
        =@user.email
        %br
        Password: ********
        %p
        = link_to 'edit', edit_user_registration_path, class: 'btn btn-primary'
        %p
        Last Sign In:
        =@user.last_sign_in_at
        From:
        =@user.last_sign_in_ip

    %label Registration Code:
    %dl
      = @user.registration_code
    %p

    %label User Information:
    = link_to 'Create Instructor', "#modal-create-instructor", :data => {:toggle=>"modal"}, class: 'btn btn-primary', onclick: "$('#modal-create-instructor').find('#email').val(''); $('#modal-create-instructor').find('#name').val(''); $('#modal-create-instructor').find('#organization').val('');"

    %div
      %dl
        %label Instructors:
        %table.table#instructors-table
          %tr
            %th Name
            %th Email
            %th Organization
            %th
            %th
            %th
          - @instructors.each do |user|
            %tr{ id: "user-#{user.id}"}
              %td= user.name
              %td= user.email
              %td= user.organization
              %td= link_to 'delete', admin_user_delete_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to delete Instructor #{user.name}?" }
              %td= link_to 'make student', admin_instructor_to_student_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to make Instructor #{user.name} a student? This will erase all students accounts belonging to instructor." }
              %td= link_to 'reset password', admin_reset_password_path(id: user.id), remote: true, method: :post, :data => { :confirm => "This will assign the user a random password and email it to them. Are you sure?" }

      %dl
        %label Students:
        %table.table#students-table
          %tr
            %th Name
            %th Email
            %th Organization
            %th
          - @students.each do |user|
            %tr{ id: "user-#{user.id}" }
              %td= user.name
              %td= user.email
              %td= user.organization
              %td= link_to 'delete', admin_user_delete_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to delete Student #{user.name}?" }
              %td= link_to 'make instructor', admin_student_to_instructor_path(id: user.id), remote: true, method: :post, :data => { :confirm => "Are you sure you want to make Student #{user.name} an instructor?" }
              %td= link_to 'reset password', admin_reset_password_path(id: user.id), remote: true, method: :post, :data => { :confirm => "This will assign the user a random password and email it to them. Are you sure?" }

      %dl
        %label Student Groups:
        = link_to 'Create Student Group', '#modal-student-group-create', data: {toggle: "modal"}, class: 'btn btn-primary', onclick: "$('#modal-student-group-create').find('#name-div').removeClass('has-error'); $('#modal-student-group-create').find('#name').val(''); $('#modal-student-group-create').find('#name-help').html(''); "
        %dl{ id: "student-groups" }
          - @user.student_groups.each do |student_group|
            %div{ id: "student-group-#{student_group.id}"}
              %label
                = student_group.name
              - if student_group.name != "All"
                = link_to 'delete', admin_student_group_destroy_path(student_group_id: student_group.id), remote: true, method: :post, data: { confirm: "Are you sure you want to delete Student Group #{student_group.name}?" }
              %table.table{ id: "student-group-#{student_group.id}-table"}
                %tr
                  %th Name
                  %th Email
                  %th Organization
                  %th
                  %th
                - student_group.student_group_users.each do |sgu|
                  %tr{ id: "student-group-user-#{sgu.id}" }
                    %td= sgu.user.name
                    %td= sgu.user.email
                    %td= sgu.user.organization
                    - if student_group.name == "All"
                      %td
                        = link_to 'add to student group', '#modal-student-group-user-add', data: {toggle: "modal"}, onclick: "$('#modal-student-group-user-add').find('#user-name').html('#{sgu.user.name}'); $('#modal-student-group-user-add').find('#user_id').val('#{sgu.user.id}'); $('#modal-student-group-user-add').find('#name-div').removeClass('has-error'); $('#modal-student-group-user-add').find('#student_group_name').val(''); $('#modal-student-group-user-add').find('#name-help').html('');"
                    - else
                      %td
                        = link_to 'remove', admin_student_group_user_remove_path(student_group_user_id: sgu.id), remote: :true, method: :post, data: { confirm: "Are you sure you want to delete Student Group User #{sgu.user.name}?" }

app/views/admin/instructor_create.js.erb
<% if @user.errors.any? %>
    <% if @user.errors[:email].any? %>
        $('#modal-create-instructor').find('#email-div').addClass('has-error');
        $('#modal-create-instructor').find('#email-help').text('<%= @user.errors[:email][0] %>');
    <% end %>
    <% if @user.errors[:name].any? %>
        $('#modal-create-instructor').find('#name-div').addClass('has-error');
        $('#modal-create-instructor').find('#name-help').text('<%= @user.errors[:name][0] %>');
    <% end %>
    <% if @user.errors[:organization].any? %>
        $('#modal-create-instructor').find('#organization-div').addClass('has-error');
        $('#modal-create-instructor').find('#organization-help').text('<%= @user.errors[:organization][0] %>');
    <% end %>
<% else %>
    $('#instructors-table').append("<tr id='instructor-<%= @user.id %>'><td><%= @user.name %></td><td><%= @user.email %></td><td><%= @user.organization %></td><td><a href='/admin/instructor_delete?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true'>delete</a></td></tr>"); 
    $('#modal-create-instructor').modal('toggle');
<% end %>

app/views/admin/instructor_to_student.js.erb
$('#user-<%= @user.id %>').remove();
$('#students-table').append("<tr id='user-<%= @user.id %>'><td><%= @user.name %></td><td><%= @user.email %></td><td><%= @user.organization %></td><td><a href='/admin/user_delete?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to delete Student <%= @user.name %>?'>delete</a></td><td><a href='/admin/student_to_instructor?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to make Student <%= @user.name %> an instructor?'>make instructor</a></td></tr>");

app/views/admin/reset_password.js.erb
<% if @user.errors.any? %>
	alert('Something went wrong, unable to assign new password.');
<% else %>
	alert('A random password has been assigned to user and emailed to them at <%= @user.email %>');
<% end %>

app/views/admin/student_group_create.js.erb
<% if @student_group.errors.any? %>
  <% if @student_group.errors[:name].any? %>
    $('#modal-student-group-create').find('#name-div').addClass('has-error');
    $('#modal-student-group-create').find('#name-help').text('<%= @student_group.errors[:name][0] %>');
  <% end %>
<% else %>
  $('#student-groups').append("<div id='student-group-<%= @student_group.id %>'> <label><%= @student_group.name %></label> <a href='/admin/student_group_destroy?student_group_id=<%= @student_group.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to delete Student Group <%= @student_group.name %>'>delete</a> <table id='student-group-<%= @student_group.id %>-table' class='table'><tr><th>Name</th><th>Email</th><th>Organization</th></tr></table></div>");
  $('#modal-student-group-create').modal('toggle');
  update_flash("Created Student Group '<%= @student_group.name %>'.");
<% end %>

app/views/admin/student_group_delete.js.erb
<% if @student_group.errors.any? %>
  alert('Error destroying student group.');
<% else %>
	$('#student-group-<%= @student_group.id %>').remove();
<% end %>

app/views/admin/student_group_user_add.js.erb
<% if @student_group_user %>
	<% if @student_group.errors.any? %>
	  alert('Error add user to student group.');
	<% else %>
		<% if @student_group_user.errors.any? %>
			<% if @student_group_user.errors[:user].any? %>
				$('#modal-student-group-user-add').find('#name-div').addClass('has-error');
  			$('#modal-student-group-user-add').find('#name-help').text('User already exists in Student Group <%= @student_group.name %>');
  		<% end %>
		<% else %>
			$('#modal-student-group-user-add').modal('toggle');
			$('#student-group-<%= @student_group.id %>-table').append("<tr id='student-group-user-<%= @student_group_user.id %>'><td><%= @student_group_user.user.name %></td><td><%= @student_group_user.user.email %></td><td><%= @student_group_user.user.organization %></td><td><a href='/admin/student_group_user_remove?student_group_user_id=<%= @student_group_user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to delete Student Group User <%= @student_group_user.user.name %>'>remove</a></td></tr>")
		<% end %>
	<% end %>
<% else %>
  $('#modal-student-group-user-add').find('#name-div').addClass('has-error');
  $('#modal-student-group-user-add').find('#name-help').text('could not find Student Group');
<% end %>

app/views/admin/student_group_user_remove.js.erb
$('#student-group-user-<%= @student_group_user.id %>').remove();

app/views/admin/student_to_instructor.js.erb
$('#user-<%= @user.id %>').remove();
$('#instructors-table').append("<tr id='user-<%= @user.id %>'><td><%= @user.name %></td><td><%= @user.email %></td><td><%= @user.organization %></td><td><a href='/admin/user_delete?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='re you sure you want to delete Instructor <%= @user.name %>?'>delete</a></td><td><a href='/admin/instructor_to_student?id=<%= @user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to make Instructor <%= @user.name %> a student? This will erase all students accounts belonging to instructor.'>make student</a></td></tr>");

app/views/admin/user_delete.js.erb
$('#user-<%= @user.id %>').remove();