config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'boot_status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController
  before_action :authenticate_admin_or_instructor
  before_action :set_user

  # Scenario
  before_action :set_scenario, only: [
    :clone, :destroyme, :edit, :modify, :show, :update, :save, :save_as,
    :boot, :boot_status, :unboot, :pause, :start,
    :cloud_add, 
    :player_modify, :player_student_group_add, :player_add, :player_group_add, :player_delete, :player_group_admin_access_add, :player_group_user_access_add,
    :role_recipe_add, :role_add,
    :recipe_custom_add, :recipe_global_add, :recipe_global_get, :recipe_remove, :recipe_update, :recipe_update_view, :recipe_view,
    :group_add
  ]

  # Cloud
  before_action :set_cloud, only: [
    :boot_cloud, :unboot_cloud, :cloud_delete, :cloud_modify, :subnet_add
  ]

  # Subnet
  before_action :set_subnet, only: [
    :boot_subnet, :unboot_subnet, :subnet_delete, :subnet_modify, :instance_add
  ]

  # Instance
  before_action :set_instance, only: [
    :boot_instance, :unboot_instance, :instance_role_add, :instance_delete, :instance_bash_history, :instance_chef_error, :instance_modify
  ]

  # Group
  before_action :set_group, only: [
    :group_delete, :group_modify, :group_admin_access_add, :group_user_access_add, :group_player_add, :group_student_group_add, :group_student_group_remove
  ]
  before_action :set_instance_group, only: [
    :group_admin_access_remove, :group_user_access_remove
  ]
  before_action :set_player, only: [
    :group_player_delete
  ]

  # Role
  before_action :set_role, only: [
    :role_recipe_add, :role_delete, :role_modify
  ]
  before_action :set_recipe, only: [
    :recipe_remove, :recipe_update, :recipe_update_view, :recipe_update, :recipe_view
  ]
  before_action :set_role_recipe, only: [
    :role_recipe_remove
  ]
  before_action :set_instance_role, only: [
    :instance_role_remove
  ]

  # GET /scenarios
  # GET /scenarios.json
  def index
    @scenarios = []
    if @user.is_admin?
      @scenarios = Scenario.all
    else
      @scenarios = Scenario.where(user_id: current_user.id)
    end
  end

  # GET /scenarios/1
  # GET /scenarios/1.json
  def show
    # @clone = params[:clone]
    @scenario.check_status
  end

  # GET /scenarios/new
  def new
    @scenario = Scenario.new
    @templates = YmlRecord.yml_headers
    @templates_user = YmlRecord.yml_headers_user(@user)
    puts @templates
    puts
    puts @templates_user
  end

  # GET /scenarios/1/edit
  def edit
    @templates = []
  end

  # POST /scenarios
  # POST /scenarios.json
  def create
    # scrub this template input
    if template = scenario_params["template"]
      @scenario = YmlRecord.load_yml(scenario_params["template"], @user)
    else
      @scenario = Scenario.new(scenario_params)
    end

    respond_to do |format|
      if @scenario.save
        format.html { redirect_to @scenario, notice: 'Scenario was successfully created.' }
        format.json { render :show, status: :created, location: @scenario }
      else
        format.html { render :new }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenarios/1
  # PATCH/PUT /scenarios/1.json
  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html { redirect_to @scenario, notice: 'Scenario was successfully updated.' }
        format.json { render :show, status: :ok, location: @scenario }
      else
        format.html { render :edit }
        format.json { render json: @scenario.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_custom
    @scenario = Scenario.new(name: params[:name], custom: true, user_id: @user.id)
    if @scenario.make_custom
      @scenario.save
    end

    respond_to do |format|
      format.js { render "scenarios/js/scenario/create_custom.js.erb", layout: false }
    end
  end

  def obliterate_custom
    @filename = params[:filename]
    path = "#{Settings.app_path}/scenarios/user/#{@user.id}/#{params[:filename]}"
    if not File.exists? path
      @error = "does not exist."
    end
    FileUtils.rm_r path

    respond_to do |format|
      format.js { render "scenarios/js/scenario/obliterate_custom.js.erb", layout: false }
    end
  end

  def destroyme

    if not @scenario.custom?
      if @scenario.destroy
        respond_to do |format|
          format.js { render js: "window.location.pathname='/scenarios'" }
        end
      else
        respond_to do |format|
          format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
        end
      end
    elsif params[:save] == nil and @scenario.modified?
      respond_to do |format|
        format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
      end
    else
      if params[:save] == "true"
        @scenario.update_yml
      end
      if @scenario.destroy
        respond_to do |format|
          format.js { render js: "window.location.pathname='/scenarios'" }
        end
      else 
        respond_to do |format|
          format.js { render 'scenarios/js/scenario/destroy.js.erb', :layout => false }
        end
      end
    end

  end

  def save
    @scenario.update_yml
    respond_to do |format|
      format.js { render 'scenarios/js/scenario/save.js.erb', :layout => false }
    end
  end

  def save_as
    @scenario.change_name(params[:name])
    respond_to do |format|
      format.js { render 'scenarios/js/scenario/save_as.js.erb', :layout => false }
    end
  end

  def clone
    @clone = @scenario.clone(params[:name])
    respond_to do |format|
      format.js { render "scenarios/js/scenario/clone.js.erb", layout: false }
    end
  end

  def clone_set
    clone = Scenario.find(params[:clone_id])
    redirect_to clone, notice: 'Scenario was successfully cloned.'
  end

  #############################################################
  # BOOTING

  def boot
    @scenario.boot(dependents: true)
    respond_to do |format|
      format.js { render 'scenarios/js/boot/boot_scenario.js.erb', :layout => false }
    end
  end

  def unboot
    @scenario.unboot(dependents: true)
    respond_to do |format|
      format.js { render 'scenarios/js/boot/unboot_scenario.js.erb', :layout => false }
    end
  end

  def boot_cloud
    @cloud.boot(solo: true)
    respond_to  do |format|
      format.js { render template: 'scenarios/js/boot/boot_cloud.js.erb', layout: false }
    end
  end

  def unboot_cloud
    @cloud.unboot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/unboot_cloud.js.erb',  layout: false }
    end
  end

  def boot_subnet
    @subnet.boot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/boot_subnet.js.erb', layout: false }
    end
  end

  def unboot_subnet
    @subnet.unboot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/unboot_subnet.js.erb', layout: false }
    end
  end

  def boot_instance
    @instance.boot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/boot_instance.js.erb', layout: false }
    end
  end

  def unboot_instance
    @instance.unboot(solo: true)
    respond_to do |format|
      format.js { render template: 'scenarios/js/boot/unboot_instance.js.erb', layout: false }
    end
  end

  def boot_status
    respond_to do |format|
      format.js { render 'scenarios/js/boot/boot_status.js.erb', :layout => false }
    end
  end

  def pause
    @scenario.pause
    respond_to do |format|
      format.js { render 'scenarios/js/boot/pause.js.erb', :layout => false }
    end
  end

  def start
    @scenario.start
    respond_to do |format|
      format.js { render 'scenarios/js/boot/start.js.erb', :layout => false }
    end
  end

  ###############################################################
  #  Resource Modification

  # CLOUD
  def cloud_add
    @cloud = @scenario.clouds.new(name: params[:name], cidr_block: params[:cidr_block])
    @cloud.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/cloud/add.js.erb', layout: false }
    end
  end

  def cloud_delete
    @cloud.destroy
    respond_to do |format|
      format.js { render template: 'scenarios/js/cloud/delete.js.erb', layout: false }
    end
  end

  def cloud_modify
    @cloud.update(name: params[:name], cidr_block: params[:cidr_block])

    respond_to do |format|
      format.js { render template: 'scenarios/js/cloud/modify.js.erb', layout: false }
    end
  end

  # SUBNET
  def subnet_add
    @subnet = @cloud.subnets.new(name: params[:name], cidr_block: params[:cidr_block], internet_accessible: params[:internet_accessible])
    @subnet.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/subnet/add.js.erb', layout: false }
    end
  end

  def subnet_delete
    @subnet.destroy
    respond_to do |format|
      format.js { render template: 'scenarios/js/subnet/delete.js.erb', layout: false }
    end
  end

  def subnet_modify
    @subnet.update(name: params[:name], cidr_block: params[:cidr_block], internet_accessible: params[:internet_accessible])

    respond_to do |format|
      format.js { render template: 'scenarios/js/subnet/modify.js.erb', layout: false }
    end
  end

  # INSTANCE
  def instance_add
    @instance = @subnet.instances.new(
      name: params[:name],
      ip_address: params[:ip],
      os: params[:os],
      internet_accessible: params[:internet_accessible],
      uuid: `uuidgen`.chomp
    )
    @instance.save

    respond_to do |format|
      format.js { render template: 'scenarios/js/instance/add.js.erb', layout: false }
    end
  end

  def instance_delete
    @instance.destroy
    respond_to do |format|
      format.js { render template: 'scenarios/js/instance/delete.js.erb', layout: false }
    end
  end

  def instance_modify

app/helpers/scenarios_helper.rb
module ScenariosHelper
end

app/views/scenarios/edit.html.haml
%h1 Editing scenario

= render 'form'

= link_to 'Show', @scenario
\|
= link_to 'Back', scenarios_path

app/views/scenarios/index.html.haml
%div.modal#modal-scenario-destroy{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Changes have been made to the Scenario
      %div.modal-body.inline#modalbody
        
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Cancel

%div.modal#modal-scenario-custom-new{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Create Custom Scenario
      %div.modal-body#modalbody
        = form_tag scenarios_create_custom_path, remote:true, method: :post do
          %div#name-div
            = label_tag "Name:", nil, class: 'control-label'
            = text_field_tag "name", nil, class: 'form-control'
            %span.help-block#name-help
          %p
          %div#help-div
            %span.help-block#help-help

          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4
        Scenarios:
    %li
      &nbsp;&nbsp;
    %li
      = link_to 'Load New Scenario', new_scenario_path, class: 'btn btn-default'
    %li
      &nbsp;&nbsp;
    %li
      = link_to 'Create Custom Scenario', "#modal-scenario-custom-new", :data => {:toggle=>"modal"}, onclick: "$('#modal-scenario-custom-new').find('#name').val(''); $('#modal-scenario-custom-new').find('#name-div').removeClass('has-error'); $('#modal-scenario-custom-new').find('#name-help').html('');", class: 'btn btn-default'

  %div.panel-body
    %dl
    %h4
      %b
        Current Scenarios:
    %br
    %table.table
      %tr
        %th Name
        %th Status
        - if @user.is_admin?
          %th Instructor
        %th

      - @scenarios.each do |scenario|
        %tr
          %td= scenario.name
          %td= scenario.status
          - if @user.is_admin?
            - if scenario.user_id
              %td= User.find(scenario.user_id).name
            - else
              %td
          %td
            %div.btn-group
              = link_to 'Show', scenario, class: 'btn btn-default'
              = link_to 'Destroy', destroyme_scenario_path(scenario), method: :post, remote: true, :data => { :confirm => 'Are you sure?' }, class: 'btn btn-danger'

app/views/scenarios/new.html.haml
%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4#scenario-new-title
        New Scenario:

  %div.panel-body
    %h3 Default Scenarios:
    %ul
      - @templates.each do |template|
        %b Name:
        = template[:name]
        %br
        %b Description:
        = template[:description]
        %p
        = simple_form_for(@scenario) do |f|
          = f.hidden_field :template, :value => template[:filename]
          = f.button :submit, 'Create ' + template[:name], class: 'btn btn-primary'
        %p
        %br

    %h3 My Scenarios:
    %ul
      - @templates_user.each do |template|
        %div{ id: "scenario-custom-#{template[:filename]}" }
          %b Name:
          = template[:name]
          %br
          %b Description:
          = template[:description]
          %p
          %div.nav.nav-pills
            %li
              = simple_form_for(@scenario) do |f|
                = f.hidden_field :template, :value => template[:filename]
                = f.button :submit, 'Create ' + template[:name], class: 'btn btn-primary'
            %li
              &nbsp;&nbsp;
            %li
              = link_to 'Obliterate', scenarios_obliterate_custom_path(filename: template[:filename]), remote: true, method: :post, :data => { confirm: "This will completely erase the scenario. Are you sure?" }, class: 'btn btn-danger'
  %p
  
= link_to 'Back', scenarios_path, class: 'btn btn-default'

app/views/scenarios/show.html.haml
= render '/scenarios/show/modals'

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h4
        %b
          %span#scenario-name
            = @scenario.name
          \:
    %li
      &nbsp;
    %li{ id: 'boot-button-li', class: @scenario.bootable? ? "" : "disabled" }
      = link_to 'Boot', boot_scenario_path(@scenario), method: :post, remote:true, id: 'boot-button', class: 'btn btn-default'
    %li{ id: 'unboot-button-li', class: @scenario.unbootable? ? "" : "disabled" }
      = link_to 'Unboot', unboot_scenario_path(@scenario), method: :post, remote:true, id: 'unboot-button', class: 'btn btn-default'
    %li{ id: 'pause-button-li', class: @scenario.booted? ? "" : "disabled" }
      = link_to 'Pause', pause_scenario_path(@scenario), method: :post, remote:true, id: 'pause-button', class: 'btn btn-default'
    %li{ id: 'start-button-li', class: @scenario.paused? ? "" : "disabled" }
      = link_to 'Start', start_scenario_path(@scenario), method: :post, remote:true, id: 'start-button', class: 'btn btn-default'
    %li
      = link_to 'Clone', "#modal-scenario-clone", :data => {:toggle=>"modal"}, :onclick => "$('#modal-scenario-clone').find('#name-div').removeClass('has-error'); $('#modal-scenario-clone').find('#name').val(''); $('#modal-scenario-clone').find('#name-help').html('');", class: 'btn btn-default'
    %li{ id: 'destroy-button-li', class: @scenario.stopped? ? "" : "disabled" }
      = link_to 'Destroy', destroyme_scenario_path(@scenario), method: :post, remote: true, id: 'destroy-button', class: 'btn btn-default'
    - if @scenario.custom?
      %li{ id: "save-button-li", class: @scenario.modified? ? "" : "disabled" }
        = link_to 'Save', save_scenario_path(@scenario), method: :post, remote: true, id: 'save-button', class: 'btn btn-default', href: @scenario.modified? ? "/scenarios/#{@scenario.id}/save" : "javascript: void(0)"
      %li{ id: 'save-as-button-li', class: @scenario.stopped? ? "" : "disabled" }
        = link_to 'Save As', "#modal-scenario-save-as", :data => {:toggle=>"modal"}, id: 'save-as-button', onclick: "$('#modal-scenario-save-as').find('#name').val(''); $('#modal-scenario-save-as').find('#name-div').removeClass('has-error'); $('#modal-scenario-save-as').find('#name-help').html(''); $('#modal-scenario-save-as').find('#help-div').removeClass('has-error'); $('#modal-scenario-save-as').find('#help-help').html('');", class: 'btn btn-default'
    %li
      = link_to 'Show Log', log_get_scenario_path(@scenario, kind: 'scenario'), method: :post, remote: true, class: 'btn btn-default'

  %div.indent.panel-body
    // Instructions
    %label
      Instructions:
    %div.indent
      = @scenario.instructions
    %p

    // Scenario
    %label
      Scenario:

    %div.indent
      Status:
      %span#scenario-status
        = @scenario.status
      %div{ id: "scenario-status-dot", class: "inline-block #{@scenario.status} #{(@scenario.booting? or @scenario.unbooting?) ? 'hidden' : ''}" }
        &#9679;
      %div{ id: "scenario-spinner", class: "inline-block #{(@scenario.booting? or @scenario.unbooting?) ? 'spin' : ''}" }

      %br
      Created at:
      = @scenario.created_at
      %br

      // Clouds
      %label
        Clouds:
      %div.inline-block
        - if @scenario.custom?
          %div.dropdown
            %button.btn.btn-default.dropdown-toggle{type:'button', id:'dropdown-clouds', "data-toggle" => 'dropdown', "aria-expanded" => "true"}
              %span.caret
            %ul.dropdown-menu{role: 'menu', "aria-labelledby" => 'dropdown-clouds'}
              %li
                = link_to 'Add Cloud', "#modal-cloud-add", :data => {:toggle=>"modal"}, onclick: "$('#modal-cloud-add').find('#name').val(''); $('#modal-cloud-add').find('#name-div').removeClass('has-error'); $('#modal-cloud-add').find('#name-help').html(''); $('#modal-cloud-add').find('#cidr_block').val(''); $('#modal-cloud-add').find('#cidr-div').removeClass('has-error'); $('#modal-cloud-add').find('#cidr-help').html('');"
      %ul#clouds
        - @scenario.clouds.each do |cloud|
          = render '/scenarios/show/cloud', cloud: cloud

    // Groups
    %label
      Groups:
    - if @scenario.custom?
      %div.inline-block
        %div.dropdown{id:'dropdown-roles'}
          %button.btn.btn-default.dropdown-toggle{type:'button', id:'dropdown-button-roles', "data-toggle" => 'dropdown', "aria-expanded" => "true"}
            %span.caret
          %ul.dropdown-menu{role: 'menu', "aria-labelledby" => 'dropdown-button-roles'}
            %li{ id: 'group-add-button-li' }
              = link_to 'Add Group', "#modal-group-add", :data => {:toggle=>"modal"}, onclick: "$('#modal-group-add').find('#name').val(''); $('#modal-group-add').find('#name-div').removeClass('has-error'); $('#modal-group-add').find('#name-help').html('');", id: 'group-add-button'
    %ul#groups
      - @scenario.groups.each do |group|
        = render '/scenarios/show/group', group: group

    %p
    // Roles
    %label
      Roles:
    - if @scenario.custom?
      %div.inline-block
        %div.dropdown{id:'dropdown-roles'}
          %button.btn.btn-default.dropdown-toggle{type:'button', id:'dropdown-button-roles', "data-toggle" => 'dropdown', "aria-expanded" => "true"}
            / %span.glyphicon.glyphicon-pencil{"aria-hidden" => "true"}
            %span.caret
          %ul.dropdown-menu{role: 'menu', "aria-labelledby" => 'dropdown-button-roles'}
            %li{ id: 'role-add-button-li' }
              = link_to 'Add Role', "#modal-role-add", :data => {:toggle=>"modal"}, onclick: "$('#modal-role-add').find('#name').val(''); $('#modal-role-add').find('#name-div').removeClass('has-error'); $('#modal-role-add').find('#name-help').html('');", id: 'role-add-button'
    %ul#roles
      - @scenario.roles.each do |role|
        = render '/scenarios/show/role', role: role

    // Recipes
    %label
      Recipes:
    - if @scenario.custom?
      %div.inline-block
        %div.dropdown{id:'dropdown-recipes'}
          %button.btn.btn-default.dropdown-toggle{type:'button', id:'dropdown-button-recipes', "data-toggle" => 'dropdown', "aria-expanded" => "true"}
            %span.caret
          %ul.dropdown-menu{role: 'menu', "aria-labelledby" => 'dropdown-button-recipes'}
            %li
              = link_to 'Add Global Recipe', recipe_global_get_scenario_path(@scenario), remote: true, method: :post
            %li
              = link_to 'Add Custom Recipe', "#modal-recipe-custom-add", :data => {:toggle=>"modal"}, onclick: "$('#modal-recipe-custom-add').find('#name-div').removeClass('has-error'); $('#modal-recipe-custom-add').find('#name-help').html(''); $('#modal-recipe-custom-add').find('#name').val(''); "
    %ul#recipes
      - @scenario.recipes.each do |recipe|
        = render '/scenarios/show/recipe', recipe: recipe

= link_to 'Back', scenarios_path, class: 'btn btn-default'

%script
  - if @clone
    update_flash("Scenario successfully cloned");
%script
  = "get_boot_status('#{@scenario.id}');"
  

app/views/scenarios/status.html.haml
%h1= @scenario.name
Booted: 
= @total_booted
Total:
= @total_instances