config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'boot_status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/controllers/instructor_controller.rb
class InstructorController < ApplicationController
  before_action :authenticate_instructor
  before_action :set_student_group, only: [:student_group_destroy]

  def index
    @players = Player.where(user_id: current_user.id)
  end

  def student_group_create
    @user = User.find(current_user.id)
    @student_group = @user.student_groups.new(name: params[:name])
    @student_group.save

    respond_to do |format|
      format.js { render 'instructor/student_group_create.js.erb', :layout => false }
    end
  end

  def student_group_destroy
    @student_group.destroy
    respond_to do |format|
      format.js { render 'instructor/student_group_delete.js.erb', :layout => false }
    end
  end

  def student_group_user_add
    user = User.find(params[:user_id])
    @student_group_user = nil
    if @student_group = @user.student_groups.find_by_name(params[:student_group_name])
      @student_group_user = @student_group.user_add(user)
    end

    respond_to do |format|
      format.js { render 'instructor/student_group_user_add.js.erb', :layout => false }
    end
  end

  def student_group_user_remove
    @student_group_user = StudentGroupUser.find(params[:student_group_user_id])
    if @student_group_user.student_group.user == User.find(current_user.id)
      @student_group_user.destroy
    end

    respond_to do |format|
      format.js { render 'instructor/student_group_user_remove.js.erb', :layout => false }
    end
  end

  private

  def set_student_group
    @student_group = StudentGroup.find(params[:student_group_id])
    if not User.find(current_user.id).owns? @student_group
      head :ok, content_type: "text/html"
      return
    end
  end

end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/views/instructor/index.html.haml
%div.modal#modal-student-group-create{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Create Student Group
      %div.modal-body#modalbody
        = form_tag instructor_student_group_create_path(@scenario), remote: true, method: :post do 
          %div#name-div
            = label_tag nil, "Name:"
            = text_field_tag "name", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %br
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.modal#modal-student-group-user-add{ :tabindex => "-1", :role => "dialog", "aria-labelledby" => "myModalLabel", "aria-hidden" => "true"}
  %div.modal-dialog
    %div.modal-content
      %div.modal-header
        %button.close{ :type => "button", "data-dismiss" => "modal", "aria-hidden" => "true"}
          &times;
        %h3.modal-title.inline#title
          Add User to Student Group
      %div.modal-body#modalbody
        = form_tag instructor_student_group_user_add_path(@scenario), remote: true, method: :post do
          = label_tag nil, "User:"
          %span#user-name
          = hidden_field_tag 'user_id'
          %div#name-div
            = label_tag nil, "Student Group Name:"
            = text_field_tag "student_group_name", nil, class: 'form-control'
            %span.help-block.inline#name-help
          %br
          = submit_tag "Submit", :class => 'btn btn-default'
      %div.modal-footer
        %button.btn.btn-default{"data-dismiss" => "modal"}
          Close

%div.panel.panel-default
  %div.panel-heading.nav.nav-pills
    %li
      %h3
        Instructor Home

  %div.panel-body
    %label Account Information: 
    %div
      %dl
        Name: 
        =@user.name
        %br
        Email:
        =@user.email
        %br
        Password: ********
        %p
        = link_to 'edit', edit_user_registration_path, class: 'btn btn-primary'
        %p
        Last Sign In:
        =@user.last_sign_in_at
        From:
        =@user.last_sign_in_ip

    %label Registration Code:
    %dl
      = @user.registration_code
    %p

    %label Student Groups:
    = link_to 'Create Student Group', '#modal-student-group-create', data: {toggle: "modal"}, class: 'btn btn-primary', onclick: "$('#modal-student-group-create').find('#name-div').removeClass('has-error'); $('#modal-student-group-create').find('#name').val(''); $('#modal-student-group-create').find('#name-help').html(''); "
    %dl{ id: "student-groups" }
      - @user.student_groups.each do |student_group|
        %div{ id: "student-group-#{student_group.id}"}
          %label
            = student_group.name
          - if student_group.name != "All"
            = link_to 'delete', instructor_student_group_destroy_path(student_group_id: student_group.id), remote: true, method: :post, data: { confirm: "Are you sure you want to delete Student Group #{student_group.name}?" }
          %table.table{ id: "student-group-#{student_group.id}-table"}
            %tr
              %th Name
              %th Email
              %th Organization
              %th
              %th
            - student_group.student_group_users.each do |sgu|
              %tr{ id: "student-group-user-#{sgu.id}" }
                %td= sgu.user.name
                %td= sgu.user.email
                %td= sgu.user.organization
                - if student_group.name == "All"
                  %td
                    = link_to 'add to student group', '#modal-student-group-user-add', data: {toggle: "modal"}, onclick: "$('#modal-student-group-user-add').find('#user-name').html('#{sgu.user.name}'); $('#modal-student-group-user-add').find('#user_id').val('#{sgu.user.id}'); $('#modal-student-group-user-add').find('#name-div').removeClass('has-error'); $('#modal-student-group-user-add').find('#student_group_name').val(''); $('#modal-student-group-user-add').find('#name-help').html('');"
                - else
                  %td
                    = link_to 'remove', instructor_student_group_user_remove_path(student_group_user_id: sgu.id), remote: :true, method: :post, data: { confirm: "Are you sure you want to delete Student Group User #{sgu.user.name}?" }

    %label Running Scenarios:
    - if @players.size == 0
      %dl
        none

    - @players.each do |player|
      %dl
        - if scenario = Scenario.find(player.group.scenario_id)
          %label= scenario.name
          %dl
            %b.inline login:
            = player.login
            %br
            %b.inline password:
            = player.password
            %br
            %b.iniline instructions:
            = scenario.instructions
            %br

app/views/instructor/student_group_create.js.erb
<% if @student_group.errors.any? %>
  <% if @student_group.errors[:name].any? %>
    $('#modal-student-group-create').find('#name-div').addClass('has-error');
    $('#modal-student-group-create').find('#name-help').text('<%= @student_group.errors[:name][0] %>');
  <% end %>
<% else %>
  $('#student-groups').append("<div id='student-group-<%= @student_group.id %>'> <label><%= @student_group.name %></label> <a href='/instructor/student_group_destroy?student_group_id=<%= @student_group.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to delete Student Group <%= @student_group.name %>'>delete</a> <table id='student-group-<%= @student_group.id %>-table' class='table'><tr><th>Name</th><th>Email</th><th>Organization</th></tr></table></div>");
  $('#modal-student-group-create').modal('toggle');
  update_flash("Created Student Group '<%= @student_group.name %>'.");
<% end %>

app/views/instructor/student_group_delete.js.erb
<% if @student_group.errors.any? %>
  alert('Error destroying student group.');
<% else %>
	$('#student-group-<%= @student_group.id %>').remove();
<% end %>

app/views/instructor/student_group_user_add.js.erb
<% if @student_group_user %>
	<% if @student_group.errors.any? %>
	  alert('Error add user to student group.');
	<% else %>
		<% if @student_group_user.errors.any? %>
			<% if @student_group_user.errors[:user].any? %>
				$('#modal-student-group-user-add').find('#name-div').addClass('has-error');
  			$('#modal-student-group-user-add').find('#name-help').text('User already exists in Student Group <%= @student_group.name %>');
  		<% end %>
		<% else %>
			$('#modal-student-group-user-add').modal('toggle');
			$('#student-group-<%= @student_group.id %>-table').append("<tr id='student-group-user-<%= @student_group_user.id %>'><td><%= @student_group_user.user.name %></td><td><%= @student_group_user.user.email %></td><td><%= @student_group_user.user.organization %></td><td><a href='/instructor/student_group_user_remove?student_group_user_id=<%= @student_group_user.id %>' data-method='post' rel='nofollow' data-remote='true' data-confirm='Are you sure you want to delete Student Group User <%= @student_group_user.user.name %>'>remove</a></td></tr>")
		<% end %>
	<% end %>
<% else %>
  $('#modal-student-group-user-add').find('#name-div').addClass('has-error');
  $('#modal-student-group-user-add').find('#name-help').text('could not find Student Group');
<% end %>

app/views/instructor/student_group_user_remove.js.erb
$('#student-group-user-<%= @student_group_user.id %>').remove();