config/routes.rb
Edurange::Application.routes.draw do
  get 'management/clean'
  get 'management/status'
  get 'management/purge'

  resources :instance_groups
  resources :players
  resources :groups
  resources :instance_roles
  resources :roles
  resources :instances
  resources :subnets
  resources :clouds
  resources :statistics do
    member do  # define routing for the statistics controller methods
      # destorying statistics
      post 'destroyme'
      # downloading statistics
      get 'download'
      get 'download_all'  
      # analytics, complicated query params
      get 'generate_analytics' 
    end
  end
  

  get 'statistic/id', to: 'scenarios#id'
  

  resources :scenarios do
    member do
      post 'destroyme'

      post 'boot'
      post 'boot_cloud'
      post 'boot_subnet'
      post 'boot_instance'
      post 'unboot'
      post 'unboot_cloud'
      post 'unboot_subnet'
      post 'unboot_instance'
      post 'boot_status'
      post 'pause'
      post 'start'

      post 'log_get'
      post 'clone'
      get  'clone_set'
      post 'save'
      post 'save_as'
      post 'obliterate_custom'

      post 'cloud_add'
      post 'cloud_delete'
      post 'cloud_modify'

      post 'subnet_add'
      post 'subnet_delete'
      post 'subnet_modify'

      post 'instance_add'
      post 'instance_bash_history'
      post 'instance_chef_error'
      post 'instance_delete'
      post 'instance_modify'
      post 'instance_role_add'
      post 'instance_role_remove'

      post 'group_add'
      post 'group_modify'
      post 'group_delete'

      post 'group_player_add'
      post 'group_player_delete'
      post 'group_student_group_add'
      post 'group_student_group_remove'

      post 'group_admin_access_add'
      post 'group_admin_access_remove'
      post 'group_user_access_add'
      post 'group_user_access_remove'

      post 'role_add'
      post 'role_delete'
      post 'role_modify'
      post 'role_recipe_add'
      post 'role_recipe_remove'

      post 'recipe_view'
      post 'recipe_update_view'
      post 'recipe_global_get'
      post 'recipe_global_add'
      post 'recipe_custom_add'
      post 'recipe_remove'
      post 'recipe_update'

    end
  end

  post 'scenarios/create_custom'
  post 'scenarios/obliterate_custom'
  get 'scenarios/destroy/:id', to: 'scenarios#destroy'

  get  'admin', to: 'admin#index'
  post 'admin/user_delete'
  post 'admin/instructor_create'
  post 'admin/student_to_instructor'
  post 'admin/instructor_to_student'
  post 'admin/reset_password'
  post 'admin/student_group_create'
  post 'admin/student_group_destroy'
  post 'admin/student_group_user_add'
  post 'admin/student_group_user_remove'

  get 'instructor', to: 'instructor#index'
  post 'instructor/student_group_create'
  post 'instructor/student_group_destroy'
  post 'instructor/student_group_user_add'
  post 'instructor/student_group_user_remove'

  get 'student', to: 'student#index'

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/role.rb
class Role < ActiveRecord::Base
  belongs_to :scenario
  has_many :role_recipes, dependent: :destroy
  has_many :recipes, through: :role_recipes
  has_many :instance_roles, dependent: :destroy
  has_one :user, through: :scenario

  serialize :packages, Array

  validates :name, presence: true, uniqueness: { scope: :scenario, message: "Name taken" }
  validate :instances_stopped

  before_destroy :instances_stopped, prepend: :true
  after_destroy :update_scenario_modified

  def instances_stopped
    self.instance_roles.each do |instance_role|
      if not instance_role.instance.stopped?
        errors.add(:running, "instances using this role must be stopped before deletion")
        return false
      end
    end
    if self.scenario.custom?
      self.scenario.update(modified: true)
    end
    true
  end

  def update_scenario_modified
    if self.scenario.custom?
      self.scenario.update_attribute(:modified, true)
    end
    true
  end

  def instances_stopped?
    self.instance_roles.each do |instance_role|
      return false if not instance_role.instance.stopped? 
    end
    true
  end

end

app/views/scenarios/js/role/add.js.erb
<% if @role.errors.any? %>
  <% if @role.errors[:name].any? %>
    $('#modal-role-add').find('#name-div').addClass('has-error');
    $('#modal-role-add').find('#name-help').text('<%= @role.errors[:name][0] %>');
  <% end %>
<% else %>
  $('#roles').append("<%= escape_javascript( render('/scenarios/show/role', role: @role).delete("\n") ).html_safe %>");
  $('#modal-role-add').modal('toggle');
  $('#save-button-li').attr('class', '');
  $('#save-button').attr('href', '/scenarios/<%= @role.scenario.id %>/save');
  update_flash("Added role '<%= @role.name %>' to scenario.");
<% end %>

app/views/scenarios/js/role/delete.js.erb
$('#role-<%= @role.id %>-dropdown').removeClass('open');
<% if @role.errors.any? %>
  <% if @role.errors[:running].any? %>
    alert('<%= @role.errors[:running][0] %>');
  <% end %>
<% else %>
	<% @instance_role_ids.each do |instance_role_id| %>
		$('#instance-role-<%= instance_role_id %>').remove();
	<% end %>
	$('#role-<%= @role.id %>').remove();
	$('#save-button-li').attr('class', '');
	$('#save-button').attr('href', '/scenarios/<%= @role.scenario.id %>/save');
	update_flash("Removed role '<%= @role.name %>' from scenario.");
<% end %>

app/views/scenarios/js/role/modify.js.erb
<% if @role.errors.any? %>
  <% if @role.errors[:name].any? %>
    $('#modal-role-modify').find('#name-div').addClass('has-error');
    $('#modal-role-modify').find('#name-help').text('<%= @role.errors[:name][0] %>');
  <% end %>
  <% if @role.errors[:running].any? %>
    $('#modal-role-modify').find('#help-div').addClass('has-error');
    $('#modal-role-modify').find('#help-help').text('<%= @role.errors[:running][0] %>');
  <% else %>
    $('#modal-role-modify').find('#help-div').removeClass('has-error');
    $('#modal-role-modify').find('#help-help').text('');
  <% end %>
<% else %>
	<% @role.instance_roles.each do |instance_role| %>
		$('#instance-role-<%= instance_role.id %>').find('#name').html('<%= @role.name %>');
	<% end %>

	$('#role-<%= @role.id %>').find('#role-name').html('<%= @role.name %>');
  $('#modal-role-modify').modal('toggle');
  $('#save-button-li').attr('class', '');
  $('#save-button').attr('href', '/scenarios/<%= @role.scenario.id %>/save');
  update_flash("Modified role '<%= @role.name %>'.");
<% end %>

app/views/scenarios/js/role/recipe_add.js.erb
<% if @recipe %>
  <% if @recipe.errors.any? %>
    <% if @recipe.errors[:name].any? %>
      $('#modal-role-recipe-add').find('#name-div').addClass('has-error');
      $('#modal-role-recipe-add').find('#name-help').text('<%= @recipe.errors[:name][0] %>');
    <% end %>
  <% else %>
    <% if @role_recipe.errors.any? %>
      <% if @role_recipe.errors[:recipe_id].any? %>
        $('#modal-role-recipe-add').find('#name-div').addClass('has-error');
        $('#modal-role-recipe-add').find('#name-help').text('<%= @role_recipe.errors[:recipe_id][0] %>');
      <% end %>
      <% if @role_recipe.errors[:running].any? %>
        $('#modal-role-recipe-add').find('#help-div').addClass('has-error');
        $('#modal-role-recipe-add').find('#help-help').text('<%= @role_recipe.errors[:running][0] %>');
      <% else %>
        $('#modal-role-recipe-add').find('#help-div').removeClass('has-error');
        $('#modal-role-recipe-add').find('#help-help').text('');
      <% end %>
    <% else %>
      $('#role-<%= @role.id %>-recipes').append("<li id='role-recipe-<%= @role_recipe.id %>'><%= @role_recipe.recipe.name %> <a href='/scenarios/<%= @role.scenario.id %>/role_recipe_remove?role_recipe_id=<%= @role_recipe.id %>' data-method='post' rel='nofollow' data-remote='true'>remove</a></li>");
      $('#modal-role-recipe-add').modal('toggle');
      $('#save-button-li').attr('class', '');
      $('#save-button').attr('href', '/scenarios/<%= @recipe.scenario.id %>/save');
      update_flash("Added role '<%= @role.name %>' to scenario.");
    <% end %>
  <% end %>
<% else %>
  $('#modal-role-recipe-add').find('#name-div').addClass('has-error');
  $('#modal-role-recipe-add').find('#name-help').text('Recipe not found');
<% end %>

app/views/scenarios/js/role/recipe_remove.js.erb
$('#role-recipe-<%= @role_recipe.id %>').remove();
$('#save-button-li').attr('class', '');
$('#save-button').attr('href', '/scenarios/<%= @role_recipe.scenario.id %>/save');